version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jorge
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ecommerce-orm
    ports:
      - 5432:5432